# app/constants/metrics.py
"""
Friendly-key  →  raw metric column exactly as stored in
financial.financial_fact.metric
"""

# ─────────────────────────  INCOME STATEMENT  ─────────────────────────
IS_METRICS = {
    "revenue": "revenue",
    "cost_of_revenue": "costOfRevenue",
    "gross_profit": "grossProfit",
    "r_and_d": "researchAndDevelopmentExpenses",
    "general_admin_exp": "generalAndAdministrativeExpenses",
    "selling_marketing_exp": "sellingAndMarketingExpenses",
    "sga_exp": "sellingGeneralAndAdministrativeExpenses",
    "other_expenses": "otherExpenses",
    "operating_expenses": "operatingExpenses",
    "cost_and_expenses": "costAndExpenses",
    "net_interest_income": "netInterestIncome",
    "interest_income": "interestIncome",
    "interest_expense": "interestExpense",
    "depreciation_amortization": "depreciationAndAmortization",
    "ebitda": "ebitda",
    "ebit": "ebit",
    "non_operating_income_ex_interest": "nonOperatingIncomeExcludingInterest",
    "operating_income": "operatingIncome",
    "other_income_expenses_net": "totalOtherIncomeExpensesNet",
    "income_before_tax": "incomeBeforeTax",
    "income_tax_expense": "incomeTaxExpense",
    "net_income_continuing": "netIncomeFromContinuingOperations",
    "net_income_discontinued": "netIncomeFromDiscontinuedOperations",
    "other_adjustments_net_income": "otherAdjustmentsToNetIncome",
    "net_income": "netIncome",
    "net_income_deductions": "netIncomeDeductions",
    "bottom_line_net_income": "bottomLineNetIncome",
    "eps_basic": "eps",
    "eps_diluted": "epsDiluted",
    "weighted_avg_shares_out": "weightedAverageShsOut",
    "weighted_avg_shares_out_dil": "weightedAverageShsOutDil",
}

# ─────────────────────────  BALANCE SHEET  ────────────────────────────
BS_METRICS = {
    "cash": "cashAndCashEquivalents",
    "short_term_investments": "shortTermInvestments",
    "cash_and_st_invest": "cashAndShortTermInvestments",
    "net_receivables": "netReceivables",
    "accounts_receivable": "accountsReceivables",
    "other_receivables": "otherReceivables",
    "inventory": "inventory",
    "prepaids": "prepaids",
    "other_current_assets": "otherCurrentAssets",
    "total_current_assets": "totalCurrentAssets",
    "pp&e_net": "propertyPlantEquipmentNet",
    "goodwill": "goodwill",
    "intangible_assets": "intangibleAssets",
    "goodwill_intangibles": "goodwillAndIntangibleAssets",
    "long_term_investments": "longTermInvestments",
    "tax_assets": "taxAssets",
    "other_non_current_assets": "otherNonCurrentAssets",
    "total_non_current_assets": "totalNonCurrentAssets",
    "other_assets": "otherAssets",
    "total_assets": "totalAssets",
    "total_payables": "totalPayables",
    "accounts_payable": "accountPayables",
    "other_payables": "otherPayables",
    "accrued_expenses": "accruedExpenses",
    "short_term_debt": "shortTermDebt",
    "capital_lease_oblig_current": "capitalLeaseObligationsCurrent",
    "tax_payables": "taxPayables",
    "deferred_revenue": "deferredRevenue",
    "other_current_liabilities": "otherCurrentLiabilities",
    "total_current_liabilities": "totalCurrentLiabilities",
    "long_term_debt": "longTermDebt",
    "deferred_revenue_non_current": "deferredRevenueNonCurrent",
    "deferred_tax_liab_non_current": "deferredTaxLiabilitiesNonCurrent",
    "other_non_current_liabilities": "otherNonCurrentLiabilities",
    "total_non_current_liabilities": "totalNonCurrentLiabilities",
    "other_liabilities": "otherLiabilities",
    "capital_lease_oblig": "capitalLeaseObligations",
    "total_liabilities": "totalLiabilities",
    "treasury_stock": "treasuryStock",
    "preferred_stock": "preferredStock",
    "common_stock": "commonStock",
    "retained_earnings": "retainedEarnings",
    "paid_in_capital": "additionalPaidInCapital",
    "accum_oci": "accumulatedOtherComprehensiveIncomeLoss",
    "other_equity": "otherTotalStockholdersEquity",
    "total_stockholders_equity": "totalStockholdersEquity",
    "total_equity": "totalEquity",
    "minority_interest": "minorityInterest",
    "liabilities_and_equity": "totalLiabilitiesAndTotalEquity",
    "total_investments": "totalInvestments",
    "total_debt": "totalDebt",
    "net_debt": "netDebt",
}

# ─────────────────────────  CASH FLOW  ────────────────────────────────
CF_METRICS = {
    "net_income": "netIncome",
    "depreciation_amortization": "depreciationAndAmortization",
    "deferred_income_tax": "deferredIncomeTax",
    "stock_based_comp": "stockBasedCompensation",
    "change_in_working_capital": "changeInWorkingCapital",
    "accounts_receivables": "accountsReceivables",
    "inventory": "inventory",
    "accounts_payables": "accountsPayables",
    "other_working_capital": "otherWorkingCapital",
    "other_non_cash_items": "otherNonCashItems",
    "operating_cash_flow": "netCashProvidedByOperatingActivities",
    "capex": "investmentsInPropertyPlantAndEquipment",
    "acquisitions_net": "acquisitionsNet",
    "purchases_investments": "purchasesOfInvestments",
    "sales_maturities_invest": "salesMaturitiesOfInvestments",
    "other_investing_activities": "otherInvestingActivities",
    "investing_cash_flow": "netCashProvidedByInvestingActivities",
    "net_debt_issuance": "netDebtIssuance",
    "long_term_net_debt_issuance": "longTermNetDebtIssuance",
    "short_term_net_debt_issuance": "shortTermNetDebtIssuance",
    "net_stock_issuance": "netStockIssuance",
    "net_common_stock_issuance": "netCommonStockIssuance",
    "common_stock_issued": "commonStockIssuance",
    "common_stock_repurchased": "commonStockRepurchased",
    "net_pref_stock_issuance": "netPreferredStockIssuance",
    "net_dividends_paid": "netDividendsPaid",
    "common_dividends_paid": "commonDividendsPaid",
    "preferred_dividends_paid": "preferredDividendsPaid",
    "other_financing_activities": "otherFinancingActivities",
    "financing_cash_flow": "netCashProvidedByFinancingActivities",
    "fx_effect": "effectOfForexChangesOnCash",
    "net_change_in_cash": "netChangeInCash",
    "cash_end_period": "cashAtEndOfPeriod",
    "cash_begin_period": "cashAtBeginningOfPeriod",
    "operating_cash_flow_alt": "operatingCashFlow",
    "capital_expenditure": "capitalExpenditure",
    "free_cash_flow": "freeCashFlow",
    "income_taxes_paid": "incomeTaxesPaid",
    "interest_paid": "interestPaid",
}

STATEMENT_MAP = {"IS": IS_METRICS, "BS": BS_METRICS, "CF": CF_METRICS}
